# Generated by Django 3.2 on 2021-04-28 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
