# Generated by Django 3.2 on 2021-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_contact_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
