# Generated by Django 3.2 on 2021-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(max_length=100)),
                ('about_text', models.TextField()),
                ('about_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('about_mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
    ]
