# Generated by Django 3.2 on 2021-04-28 12:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
