# Generated by Django 3.2 on 2021-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickOnBuyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_name', models.CharField(max_length=100, verbose_name='click')),
                ('click', models.IntegerField(default=0, verbose_name='click number')),
                ('first_click', models.DateField(auto_now_add=True, verbose_name='first click')),
                ('last_click', models.DateTimeField(auto_now=True, verbose_name='last click')),
            ],
        ),
        migrations.CreateModel(
            name='ClickOnBuyLinkPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=0, verbose_name='all click on buy link')),
                ('click_day', models.DateField(auto_now_add=True, verbose_name='click days')),
                ('first_click', models.DateTimeField(auto_now_add=True, verbose_name='first click')),
                ('last_click', models.DateTimeField(auto_now=True, verbose_name='last click')),
            ],
        ),
    ]
