# Generated by Django 3.2 on 2021-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, verbose_name='site views')),
                ('view_count', models.IntegerField(default=0, verbose_name='views number')),
                ('first_view', models.DateField(auto_now_add=True, verbose_name='first view')),
                ('last_view', models.DateTimeField(auto_now=True, verbose_name='last view')),
            ],
        ),
        migrations.CreateModel(
            name='SiteViewsPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='site view by day')),
                ('view_day', models.DateField(auto_now_add=True, verbose_name='view days')),
                ('first_view', models.DateTimeField(auto_now_add=True, verbose_name='first view')),
                ('last_view', models.DateTimeField(auto_now=True, verbose_name='last view')),
            ],
        ),
    ]
