# Generated by Django 3.2.7 on 2021-10-07 09:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicity_name', models.CharField(max_length=200)),
                ('publicity_image', models.FileField(upload_to='publicities')),
                ('publicity_url', models.URLField(verbose_name='publicity website url')),
                ('publicity_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('publicity_mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('publicity_disponibility', models.BooleanField(default=False, verbose_name='disponibility')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0, verbose_name='product price')),
                ('product_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_image', models.FileField(upload_to='products')),
                ('product_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('product_mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('product_disponibility', models.BooleanField(default=False)),
                ('product_views', models.IntegerField(default=0)),
                ('product_buy', models.IntegerField(default=0, verbose_name='buy link click')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
